require("dotenv").config();

module.exports = {
  PERSONALITY_INSIGHTS_APIKEY: process.env.PERSONALITY_INSIGHTS_APIKEY,
  PERSONALITY_INSIGHTS_VERSION_DATE:
    process.env.PERSONALITY_INSIGHTS_VERSION_DATE,
  SESSION_KEY: process.env.SESSION_KEY,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI: process.env.SPOTIFY_REDIRECT_URI,
  TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_TOKEN_SECRET: process.env.TWITTER_ACCESS_TOKEN_SECRET
};
